### ISSUE TITLE
Food

### ISSUE THREAD

**Issue by tivvit** [gdg-garage/Garage-trip-3.0-organization#2]
how to solve food?

**Comment by curusarn** [comment]
- Find out what are the catering options provided directly by the accommodation owners
- Gather some ideas - e.g. BBQ, pizza, ...
- Get some people to commit to taking care of specific meal(s) - e.g. XXX takes care of dinner on Wednesday

**Comment by tivvit** [comment]
Ask for dietary restrictions.

**Comment by tivvit** [comment]
we should contact the owners and tell them what we need quite soon.

**Comment by tivvit** [comment]
we ate, I guess that was a success ;)
