### ISSUE TITLE
Coding game

### ISSUE THREAD

**Issue by tivvit** [gdg-garage/Garage-trip-3.0-organization#4]
Team bot coding game

**Comment by tivvit** [comment]
interesting platform https://www.codingame.com/contribute/new-contribution

**Comment by tivvit** [comment]
Active game author and good game https://github.com/eulerscheZahl/TowerDefense/tree/38dd2f5e7a65a9353a51c68e9dee798b15ba7501

**Comment by tivvit** [comment]
also a very nice game https://www.codingame.com/multiplayer/bot-programming/tron-battle

**Comment by tivvit** [comment]
we can try this https://www.codingame.com/cooperate - escape game

**Comment by tivvit** [comment]
Dev SDK in java https://www.codingame.com/playgrounds/25775/codingame-sdk-documentation/introduction

**Comment by tivvit** [comment]
https://www.codingame.com/multiplayer/clashofcode private sessions for competitive coding

**Comment by malytomas** [comment]
https://docs.google.com/document/d/1dum7adXeqcFiUYwVRDHdMwQxPuHg-VBU5dbjfmh77c4/edit

brainstorming spaceship trading simulation game

**Comment by tivvit** [comment]
https://github.com/gdg-garage/space-tycoon

**Comment by tivvit** [comment]
it was a huge success!
